// <auto-generated />
using ProjectFlowWebApp.Data.Contexts;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectFlowWebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260521120000_AddTasks")]
    partial class AddTasks
    {
    }
}
