// <auto-generated />
using AlphaWebApp.Data.Contexts;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AlphaWebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260521120000_AddTasks")]
    partial class AddTasks
    {
    }
}
